create extension if not exists pgcrypto;

create type public.user_role as enum ('client', 'professional', 'cashier', 'admin');
create type public.staff_access_level as enum ('viewer', 'manager');
create type public.appointment_status as enum ('pending', 'confirmed', 'cancelled', 'rescheduled');

create table public.tenants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  config_json jsonb not null default '{}'::jsonb,
  booking_buffer_minutes smallint not null default 30 check (booking_buffer_minutes between 0 and 240),
  created_at timestamptz not null default now()
);

create table public.users (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  name text not null,
  email text not null unique,
  phone text not null,
  gender text not null default 'OUTRO' check (gender in ('M', 'F', 'OUTRO')),
  role public.user_role not null default 'client',
  staff_access_level public.staff_access_level,
  job_title text,
  favorite_services jsonb not null default '[]'::jsonb,
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((role = 'client' and staff_access_level is null) or (role <> 'client' and staff_access_level is not null))
);

create table public.services (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  name text not null,
  description text,
  price numeric(10,2) not null check (price >= 0),
  duration_minutes smallint not null check (duration_minutes between 5 and 480),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.professionals (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  user_id uuid not null unique references public.users(id) on delete cascade,
  bio text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.professional_services (
  professional_id uuid not null references public.professionals(id) on delete cascade,
  service_id uuid not null references public.services(id) on delete cascade,
  primary key (professional_id, service_id)
);

create table public.working_hours (
  id bigint generated by default as identity primary key,
  professional_id uuid not null references public.professionals(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  start_time time not null,
  end_time time not null,
  check (end_time > start_time),
  unique (professional_id, day_of_week, start_time, end_time)
);

create table public.appointments (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  client_id uuid not null references public.users(id) on delete restrict,
  professional_id uuid not null references public.professionals(id) on delete restrict,
  service_id uuid not null references public.services(id) on delete restrict,
  appointment_date date not null,
  start_time time not null,
  end_time time not null,
  status public.appointment_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_time > start_time)
);

create index appointments_professional_schedule_idx on public.appointments (professional_id, appointment_date, start_time);
create index appointments_client_idx on public.appointments (client_id, appointment_date desc);
create index users_tenant_role_idx on public.users (tenant_id, role);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger users_set_updated_at before update on public.users for each row execute function public.set_updated_at();
create trigger appointments_set_updated_at before update on public.appointments for each row execute function public.set_updated_at();

insert into public.tenants (name, slug, config_json, booking_buffer_minutes)
values ('Casa Âmbar', 'casa-ambar', '{"primary":"#713112","surface":"#ffd7ab","logoText":"CASA ÂMBAR"}'::jsonb, 30)
on conflict (slug) do nothing;

alter table public.tenants enable row level security;
alter table public.users enable row level security;
alter table public.services enable row level security;
alter table public.professionals enable row level security;
alter table public.professional_services enable row level security;
alter table public.working_hours enable row level security;
alter table public.appointments enable row level security;
