import React,{useMemo,useState}from'react';
import {mascaraTelefone,somenteDigitos}from'./brasil';

function strength(password){let score=0;if(password.length>=8)score++;if(/[A-Z]/.test(password)&&/[a-z]/.test(password))score++;if(/\d/.test(password)&&/[^A-Za-z\d]/.test(password))score++;return score}

export default function AccountModal({mode,setMode,onClose,onLogin,onRegister,onForgot,services,busy,error,success}){
 const[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[phone,setPhone]=useState(''),[gender,setGender]=useState('OUTRO'),[favorites,setFavorites]=useState([]),[codigo,setCodigo]=useState(''),[novaSenha,setNovaSenha]=useState(''),[etapaRecuperacao,setEtapaRecuperacao]=useState('email');
 const score=useMemo(()=>strength(password),[password]);
 const level=score<=1?['fraca','Fraca']:score===2?['media','Média']:['forte','Forte'];
 const toggle=id=>setFavorites(items=>items.includes(id)?items.filter(item=>item!==id):[...items,id]);
 const abrirRecuperacao=()=>{setEtapaRecuperacao('email');setMode('forgot')};
 return <div className="modal-backdrop"><section className="account-modal" role="dialog" aria-modal="true" aria-labelledby="titulo-conta">
  <button className="close" type="button" onClick={onClose} aria-label="Fechar">×</button>
  <p className="eyebrow">ÁREA DO CLIENTE E EQUIPE</p>
  <h2 id="titulo-conta">{mode==='login'?'Acesse sua conta.':mode==='forgot'?'Recupere sua senha.':'Comece pelo seu cadastro.'}</h2>
  {mode!=='forgot'&&<div className="account-tabs"><button type="button" className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Entrar</button><button type="button" className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Criar conta</button></div>}
  {mode==='login'&&<form onSubmit={e=>{e.preventDefault();onLogin({email,password})}}><label>E-mail<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required minLength="3"/></label><button type="button" className="link-button" onClick={abrirRecuperacao}>Esqueci minha senha</button><button className="primary" disabled={busy}>{busy?'Entrando...':'Entrar'}</button></form>}
  {mode==='register'&&<form onSubmit={e=>{e.preventDefault();onRegister({name,email,password,phone:somenteDigitos(phone),gender,favoriteServices:favorites})}}><label>Nome completo<input autoComplete="name" value={name} onChange={e=>setName(e.target.value)} required/></label><label>E-mail<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha<input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} required minLength="8"/><span className={`password-strength ${level[0]}`}><i/><i/><i/><b>{password?`Senha ${level[1].toLowerCase()}`:'Use 8+ caracteres, maiúscula, número e símbolo.'}</b></span></label><label>WhatsApp<input type="tel" inputMode="numeric" autoComplete="tel-national" placeholder="(11) 99999-9999" value={phone} onChange={e=>setPhone(mascaraTelefone(e.target.value))} pattern="\([0-9]{2}\) [0-9]{4,5}-[0-9]{4}" required aria-describedby="ajuda-whatsapp"/><small id="ajuda-whatsapp">Somente número brasileiro, sem +55.</small></label><label>Gênero<select value={gender} onChange={e=>setGender(e.target.value)}><option value="M">Masculino</option><option value="F">Feminino</option><option value="OUTRO">Outro</option></select></label><fieldset><legend>O que você costuma agendar?</legend>{services.map(service=><label className="check" key={service.id}><input type="checkbox" checked={favorites.includes(service.id)} onChange={()=>toggle(service.id)}/>{service.name}</label>)}</fieldset><button className="primary" disabled={busy}>{busy?'Criando conta...':'Criar conta'}</button></form>}
  {mode==='forgot'&&<form onSubmit={e=>{e.preventDefault();if(etapaRecuperacao==='email'){onForgot({acao:'enviar',email});setEtapaRecuperacao('codigo')}else onForgot({acao:'confirmar',email,codigo,novaSenha})}}><label>E-mail<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label>{etapaRecuperacao==='codigo'&&<><label>Código de 6 dígitos<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength="6" value={codigo} onChange={e=>setCodigo(somenteDigitos(e.target.value))} required/></label><label>Nova senha<input type="password" autoComplete="new-password" minLength="8" value={novaSenha} onChange={e=>setNovaSenha(e.target.value)} required/></label></>}<button className="primary" disabled={busy}>{busy?(etapaRecuperacao==='email'?'Enviando...':'Alterando...'):(etapaRecuperacao==='email'?'Enviar código':'Salvar nova senha')}</button>{etapaRecuperacao==='email'&&<button type="button" className="link-button" onClick={()=>setEtapaRecuperacao('codigo')}>Já recebi um código</button>}<button type="button" className="link-button" onClick={()=>setMode('login')}>Voltar para entrar</button></form>}
  {error&&<p className="form-error" role="alert">{error}</p>}{success&&<p className="form-success" role="status">{success}</p>}
  {mode!=='forgot'&&<p className="form-hint">Contas da equipe usam o mesmo formulário de entrada.</p>}
 </section></div>
}
