import React,{useEffect,useMemo,useState}from'react';
import'./booking-extra.css';
import{mensagemErro}from'./mensagens';

const chave=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const dinheiro=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v));
const passos=['Data','Profissional','Serviço','Horário'];

export default function Booking({supabase,tenant,services,user,onHome,onDashboard,onAccount,onLogout}){
 const[etapa,setEtapa]=useState(1),[data,setData]=useState(chave(new Date())),[profissionais,setProfissionais]=useState([]),[profissional,setProfissional]=useState(null),[servico,setServico]=useState(null),[horarios,setHorarios]=useState([]),[horario,setHorario]=useState(null),[descricao,setDescricao]=useState(''),[aviso,setAviso]=useState(''),[carregando,setCarregando]=useState(false),[confirmacao,setConfirmacao]=useState(false);
 const dias=useMemo(()=>Array.from({length:14},(_,i)=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+i);return d}),[]);
 const servicosProfissional=useMemo(()=>!profissional?[]:services.filter(s=>(profissional.servicos||[]).includes(s.id)),[profissional,services]);
 useEffect(()=>{if(!supabase)return;let ativo=true;setCarregando(true);const diaSemana=new Date(`${data}T12:00:00`).getDay();supabase.from('profissionais').select('id,biografia,usuarios(nome),profissionais_servicos(servico_id),horarios_trabalho(dia_semana)').eq('ativo',true).then(({data:itens,error})=>{if(!ativo)return;if(error)setAviso(mensagemErro(error));else{const lista=(itens||[]).filter(p=>p.horarios_trabalho?.some(h=>h.dia_semana===diaSemana)).map(p=>({id:p.id,nome:p.usuarios?.nome||'Profissional',biografia:p.biografia||'Especialista',servicos:(p.profissionais_servicos||[]).map(r=>r.servico_id)}));setProfissionais(lista);if(profissional&&!lista.some(p=>p.id===profissional.id)){setProfissional(null);setServico(null);setHorario(null)}}setCarregando(false)});return()=>{ativo=false}},[data,supabase]);
 useEffect(()=>{if(!profissional||!servico||!supabase)return;let ativo=true;setCarregando(true);supabase.rpc('horarios_disponiveis',{p_profissional_id:profissional.id,p_servico_id:servico.id,p_data:data}).then(({data:itens,error})=>{if(!ativo)return;if(error)setAviso(mensagemErro(error));else setHorarios((itens||[]).map(i=>String(i.hora_inicio).slice(0,5)));setCarregando(false)});return()=>{ativo=false}},[profissional,servico,data,supabase]);
 function mudarData(valor){setData(valor);setHorario(null)}
 function escolherProfissional(p){setProfissional(p);if(p.id!==profissional?.id){setServico(null);setHorario(null)}}
 function escolherServico(s){setServico(s);if(s.id!==servico?.id)setHorario(null)}
 function irEtapa(destino){if(destino===1)return setEtapa(1);if(destino===2)return setEtapa(2);if(destino===3&&!profissional)return setAviso('Escolha um profissional antes de avançar.');if(destino===4&&(!profissional||!servico))return setAviso('Escolha o profissional e o serviço antes de avançar.');setAviso('');setEtapa(destino)}
 async function reservar(){if(!user){setConfirmacao(false);onAccount();return}setCarregando(true);const{error}=await supabase.rpc('reservar_agendamento',{p_profissional_id:profissional.id,p_servico_id:servico.id,p_data:data,p_hora_inicio:horario,p_observacao:descricao});setCarregando(false);setConfirmacao(false);setAviso(error?mensagemErro(error):'Agendamento realizado com sucesso.');if(!error){setEtapa(1);setHorario(null);setDescricao('')}}
 const config=tenant.config_json||{};
 return <div className="booking-shell"><header className="booking-header"><button className="brand" onClick={onHome}>{config.logoText||tenant.name}</button>{user?<div className="booking-actions"><button className="account" onClick={onDashboard}>Voltar à Dashboard</button><button className="account" onClick={onLogout}>Sair</button></div>:<button className="account" onClick={onAccount}>Minha conta</button>}</header><main className="booking-main"><p className="eyebrow">RESERVA ONLINE</p><h1>Seu próximo ritual começa aqui.</h1><ol className="steps">{passos.map((nome,i)=>{const numero=i+1;const liberado=numero<=2||(numero===3&&profissional)||(numero===4&&profissional&&servico);return <li key={nome} className={etapa===numero?'current':etapa>numero?'done':''}><button type="button" disabled={!liberado} aria-current={etapa===numero?'step':undefined} onClick={()=>irEtapa(numero)}><span>{numero}</span><small>{nome}</small></button></li>})}</ol>
 {etapa===1&&<section className="booking-card"><h2>Quando você quer vir?</h2><div className="date-strip">{dias.map(d=>{const valor=chave(d);return <button key={valor} className={data===valor?'selected':''} onClick={()=>mudarData(valor)}><small>{new Intl.DateTimeFormat('pt-BR',{weekday:'short'}).format(d)}</small><strong>{d.getDate()}</strong><small>{new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(d)}</small></button>})}</div><button className="primary" onClick={()=>irEtapa(2)}>Escolher profissional</button></section>}
 {etapa===2&&<section className="booking-card"><button className="back" onClick={()=>irEtapa(1)}>Voltar</button><h2>Quem vai cuidar de você?</h2>{carregando?<p className="empty">Carregando profissionais...</p>:<div className="professional-grid">{profissionais.map(p=><button key={p.id} className={profissional?.id===p.id?'selected':''} onClick={()=>escolherProfissional(p)}><span className="initials">{p.nome.slice(0,2)}</span><strong>{p.nome}</strong><small>{p.biografia}</small></button>)}</div>}{!carregando&&!profissionais.length&&<p className="empty">Não há profissionais disponíveis nesta data.</p>}<button className="primary" disabled={!profissional} onClick={()=>irEtapa(3)}>Escolher serviço</button></section>}
 {etapa===3&&<section className="booking-card"><button className="back" onClick={()=>irEtapa(2)}>Voltar</button><h2>O que vamos fazer?</h2><div className="service-list">{servicosProfissional.map(s=><button key={s.id} className={servico?.id===s.id?'selected':''} onClick={()=>escolherServico(s)}><span><strong>{s.name}</strong><small>{s.description}</small></span><b>{dinheiro(s.price)} · {s.duration_minutes} min</b></button>)}</div>{!servicosProfissional.length&&<p className="empty">Este profissional ainda não adicionou serviços ao perfil.</p>}<button className="primary" disabled={!servico} onClick={()=>irEtapa(4)}>Ver horários</button></section>}
 {etapa===4&&<section className="booking-card"><button className="back" onClick={()=>irEtapa(3)}>Voltar</button><h2>Qual horário funciona melhor?</h2>{carregando?<p className="empty">Calculando horários...</p>:<div className="slot-grid">{horarios.map(h=><button key={h} className={horario===h?'selected':''} onClick={()=>setHorario(h)}>{h}</button>)}</div>}{!carregando&&!horarios.length&&<p className="empty">Sem horários disponíveis para este dia.</p>}<label className="booking-note">Conte ao profissional o que você deseja<textarea value={descricao} onChange={e=>setDescricao(e.target.value)} maxLength="300" placeholder="Ex.: corte mais baixo nas laterais."/></label><button className="primary" disabled={!horario||carregando} onClick={()=>setConfirmacao(true)}>Revisar agendamento</button></section>}
 {aviso&&<p className="notice" role="status">{aviso}</p>}</main>{confirmacao&&<div className="booking-confirm"><section role="dialog" aria-modal="true" aria-labelledby="titulo-confirmacao"><button className="close" onClick={()=>setConfirmacao(false)} aria-label="Fechar">×</button><p className="eyebrow">CONFIRME SEUS DADOS</p><h2 id="titulo-confirmacao">Está tudo certo?</h2><dl><div><dt>Dia</dt><dd>{new Intl.DateTimeFormat('pt-BR',{dateStyle:'full'}).format(new Date(`${data}T12:00:00`))}</dd></div><div><dt>Profissional</dt><dd>{profissional?.nome}</dd></div><div><dt>Serviço</dt><dd>{servico?.name}</dd></div><div><dt>Horário</dt><dd>{horario}</dd></div><div><dt>Pedido</dt><dd>{descricao.trim()||'Sem observações adicionais.'}</dd></div></dl><button className="primary" disabled={carregando} onClick={reservar}>{carregando?'Confirmando...':'Confirmar agendamento'}</button></section></div>}</div>
}
