import React, { useEffect, useRef, useState } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { motion } from 'motion/react';
import { animate } from 'animejs';
import salonHero from './assets/salon-hero.png';
import './landing-extras.css';
import './story-carousel.css';
import './hero-profile.css';
import './staff-access.css';

gsap.registerPlugin(ScrollTrigger);

function ProfileMenu({ user, onLogout, onDashboard, onProfile, onBooking }) { const [open, setOpen] = useState(false); const whatsApp = 'https://wa.me/5511999999999?text=Olá%2C%20preciso%20de%20ajuda%20com%20minha%20conta.'; const ir=(acao)=>{setOpen(false);acao?.()}; return <div className="profile-menu"><button className="profile-trigger" aria-label="Abrir menu de perfil" aria-expanded={open} onClick={() => setOpen(!open)}><span>{user.name.split(' ').map((item) => item[0]).slice(0, 2).join('')}</span></button>{open && <div className="profile-popover"><p>MINHA CONTA</p><strong>{user.name}</strong><button onClick={()=>ir(onProfile)}>Editar perfil</button><button onClick={()=>ir(onBooking)}>Área de agendamentos</button>{['administrador','profissional','caixa'].includes(user.role) && <button onClick={()=>ir(onDashboard)}>Painel do espaço</button>}<a href={whatsApp} target="_blank" rel="noreferrer">Central de ajuda <i>↗</i></a><button className="profile-logout" onClick={onLogout}>Sair</button></div>}</div> }
export default function Landing({tenant,onBook,onAccount,user,onLogout,onDashboard,onProfile}){
 const root=useRef();useEffect(()=>{const ctx=gsap.context(()=>{gsap.from('.hero-copy>*',{y:38,opacity:0,stagger:.13,duration:.85,ease:'power3.out'});gsap.utils.toArray('.reveal').forEach(el=>gsap.from(el,{scrollTrigger:{trigger:el,start:'top 83%'},y:46,opacity:0,duration:.8,ease:'power3.out'}));gsap.timeline({scrollTrigger:{trigger:'.story',start:'top top',end:'+=2500',pin:true,scrub:1,anticipatePin:1}}).to('.story-copy',{xPercent:-20,opacity:.35,duration:.25}).to('.story-track',{xPercent:-80,duration:.75},0);},root);return()=>ctx.revert()},[]);
 useEffect(()=>{const pulse=animate('.live-dot',{scale:[1,1.45],opacity:[1,.32],duration:850,alternate:true,loop:true,ease:'inOutSine'});return()=>pulse.revert()},[]);
 const name=tenant?.name||'Capelli';return <div className="landing" ref={root}><header className="landing-nav"><button className="wordmark" onClick={()=>scrollTo({top:0,behavior:'smooth'})}>{tenant?.config_json?.logoText||name}</button><nav><a href="#experiencia">Experiência</a><a href="#servicos">Serviços</a></nav>{user?<ProfileMenu user={user} onLogout={onLogout} onDashboard={onDashboard}/>:<button className="nav-account" onClick={onAccount}>Minha conta</button>}</header><main>
 <section className="hero"><motion.div className="hero-copy" initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.8,ease:[.16,1,.3,1]}}><p className="kicker">SALÃO · BARBEARIA · SPA</p><h1>O ritual certo para o seu melhor momento.</h1><p className="hero-lead">No {name}, corte, barba, cor e bem-estar são tratados como uma experiência completa, feita sem pressa e com técnica.</p><div className="hero-actions"><button className="light-cta" onClick={onBook}>Agende um horário</button><a className="quiet-cta" href="#experiencia">Conheça o espaço</a></div></motion.div><div className="hero-scene" aria-label="Interior do salão"><img src={salonHero} alt="Interior de salão com cadeira de atendimento"/></div></section>
 <section className="marquee" aria-label="Valores da empresa"><div>corte <span>•</span> barba <span>•</span> cor <span>•</span> spa capilar <span>•</span> corte <span>•</span> barba <span>•</span> cor <span>•</span> spa capilar <span>•</span></div></section>
 <section className="chair-board reveal"><div><p className="kicker">AGENDA DE HOJE</p><h2>Escolha seu tempo. O resto acontece na cadeira.</h2></div><div className="chair-list">{[['10:30','Corte & acabamento','50 min'],['14:00','Barba clássica','35 min'],['16:30','Ritual spa capilar','75 min']].map(([hour,label,duration])=><button key={hour} onClick={onBook}><span className="live-dot" aria-hidden="true"></span><strong>{hour}</strong><span>{label}</span><small>{duration}</small><b>Reservar ↗</b></button>)}</div></section>
 <section id="servicos" className="services-section"><div className="section-intro reveal"><p className="kicker">FEITO PARA VOCÊ</p><h2>Uma agenda pensada para respeitar o seu ritmo.</h2></div><div className="bento"><article className="bento-main reveal"><span>01</span><h3>Corte que acompanha quem você é.</h3><p>Diagnóstico, técnica e acabamento para você sair se reconhecendo.</p><button onClick={onBook}>Reservar corte <i>↗</i></button></article><article className="bento-accent reveal"><span>02</span><h3>Cor com profundidade.</h3><p>Procedimentos que respeitam o fio e a sua rotina.</p></article><article className="bento-dark reveal"><span>03</span><h3>Tratamentos que ficam.</h3><p>Protocolos objetivos, definidos pelo que o seu cabelo precisa.</p></article></div></section>
 <section id="experiencia" className="story"><div className="story-copy"><p className="kicker">O NOSSO JEITO</p><h2>Menos pressa. Mais presença em cada detalhe.</h2><p>Acreditamos que um bom atendimento não é só sobre resultado. É sobre se sentir confortável, compreendido e seguro em todas as escolhas.</p></div><div className="story-carousel" aria-label="Galeria do espaço"><div className="story-track">{['salon-entry','barber-chair','spa-detail','hair-color','salon-team'].map((photo,index)=><figure className="story-photo" key={photo}><img src={`https://picsum.photos/seed/${photo}/1200/1600`} alt={`Foto ${index+1} do espaço Casa Âmbar`} loading="lazy"/><figcaption>0{index+1} / 05</figcaption></figure>)}</div></div></section>
 <section className="testimonials"><p className="kicker reveal">QUEM VIVEU</p><blockquote className="reveal">“Saí com a sensação de que alguém realmente entendeu o que eu queria, mesmo antes de eu conseguir explicar.”</blockquote><p className="reveal">Mariana R. · cliente</p></section>
 <section className="final-cta"><p className="kicker">SEU MOMENTO COMEÇA AQUI</p><h2>Pronto para reservar um tempo só seu?</h2><button className="light-cta" onClick={onBook}>Agende um horário</button></section>
 <section className="visit"><div className="visit-copy"><p className="kicker">ONDE ENCONTRAR A GENTE</p><h2>Chegue, desacelere e fique à vontade.</h2><p>{tenant?.config_json?.address||'Defina o endereço do seu espaço na configuração do tenant.'}</p><p className="visit-hours">{tenant?.config_json?.hours||'Terça a sexta · 09h às 20h\nSábado · 09h às 18h'}</p><a className="map-link" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(tenant?.config_json?.address||'São Paulo, SP')}`} target="_blank" rel="noreferrer">Abrir rotas no Google Maps ↗</a></div><div className="map-frame"><iframe title={`Mapa de ${name}`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" src={tenant?.config_json?.mapsEmbedUrl||`https://www.google.com/maps?q=${encodeURIComponent(tenant?.config_json?.address||'São Paulo, SP')}&output=embed`}/></div></section>
 </main><footer><span>{name}</span><span>Atendimento com hora marcada</span><button className="staff-access" onClick={onAccount}>Acesso da equipe</button></footer></div>
}
