import React,{useEffect,useMemo,useState}from'react';
import{mascaraCpf,mascaraTelefone,somenteDigitos,cpfValido}from'./brasil';
import'./team-dashboard.css';

const hoje=()=>new Date().toISOString().slice(0,10);
const hora=v=>String(v||'').slice(0,5);
const papelNome=p=>({administrador:'Dono(a)',caixa:'Caixa',profissional:'Profissional'}[p]||p);
const dataBr=v=>new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long'}).format(new Date(`${v}T12:00:00`));
const novoMembro=()=>({nome:'',email:'',senha:'',telefone:'',cpf:'',cargo:'Cabeleireiro(a)',papel:'profissional',nivel_acesso:'visualizador'});

export default function TeamDashboard({supabase,usuario,empresa,servicos,onInicio,onSair,perfilInicial}){
 const[aba,setAba]=useState(perfilInicial?'perfil':'agenda'),[profissionais,setProfissionais]=useState([]),[membros,setMembros]=useState([]),[clientes,setClientes]=useState([]),[profissionalId,setProfissionalId]=useState(''),[meuProfissional,setMeuProfissional]=useState(null),[meusServicos,setMeusServicos]=useState([]),[agendamentos,setAgendamentos]=useState([]),[data,setData]=useState(hoje()),[editor,setEditor]=useState(null),[clienteBusca,setClienteBusca]=useState(''),[membroEditor,setMembroEditor]=useState(null),[servicoEditor,setServicoEditor]=useState(null),[perfil,setPerfil]=useState(usuario),[aviso,setAviso]=useState(''),[salvando,setSalvando]=useState(false),[carregando,setCarregando]=useState(false);
 const papel=usuario?.papel;
 const gestor=['administrador','caixa'].includes(papel)||usuario?.nivel_acesso==='gestor';
 const podeEditar=gestor||papel==='profissional';
 const selecionado=profissionais.find(p=>p.id===profissionalId);
 const clientesFiltrados=useMemo(()=>{const termo=somenteDigitos(clienteBusca)||clienteBusca.toLowerCase().trim();if(!termo)return clientes.slice(0,50);return clientes.filter(c=>[c.nome,c.email,somenteDigitos(c.telefone),somenteDigitos(c.cpf)].some(v=>String(v||'').toLowerCase().includes(termo))).slice(0,50)},[clientes,clienteBusca]);
 const servicosDoEditor=useMemo(()=>gestor?servicos:servicos.filter(s=>meusServicos.includes(s.id)),[gestor,servicos,meusServicos]);
 const metricas=useMemo(()=>({total:agendamentos.length,confirmados:agendamentos.filter(a=>a.situacao==='confirmado').length,pendentes:agendamentos.filter(a=>a.situacao==='pendente').length}),[agendamentos]);

 async function carregarBase(){
  if(!usuario?.empresa_id)return;setCarregando(true);
  const[profs,clis,memb,meu]=await Promise.all([
   supabase.from('profissionais').select('id,usuario_id,biografia,usuarios(id,nome,email,telefone,cpf,cargo,papel,nivel_acesso)').eq('empresa_id',usuario.empresa_id).eq('ativo',true).order('criado_em'),
   supabase.from('usuarios').select('id,nome,email,telefone,cpf').eq('empresa_id',usuario.empresa_id).eq('papel','cliente').order('nome'),
   gestor?supabase.from('usuarios').select('id,nome,email,telefone,cpf,cargo,papel,nivel_acesso').eq('empresa_id',usuario.empresa_id).neq('papel','cliente').order('nome'):Promise.resolve({data:[]}),
   supabase.from('profissionais').select('id,usuario_id').eq('usuario_id',usuario.id).maybeSingle()
  ]);
  const erro=profs.error||clis.error||memb.error||meu.error;if(erro)setAviso(erro.message);else{setProfissionais(profs.data||[]);setClientes(clis.data||[]);setMembros(memb.data||[]);setMeuProfissional(meu.data||null);setProfissionalId(id=>id||(gestor?profs.data?.[0]?.id:meu.data?.id)||'')};setCarregando(false);
 }
 async function carregarAgenda(){if(!profissionalId)return;const{data:itens,error}=await supabase.from('agendamentos').select('id,data_agendamento,hora_inicio,hora_fim,situacao,observacao,cliente_id,profissional_id,servico_id,usuarios(nome,telefone),servicos(nome,duracao_minutos)').eq('profissional_id',profissionalId).eq('data_agendamento',data).order('hora_inicio');if(error)setAviso(error.message);else setAgendamentos(itens||[])}
 async function carregarServicos(){if(!meuProfissional?.id)return;const{data:itens,error}=await supabase.from('profissionais_servicos').select('servico_id').eq('profissional_id',meuProfissional.id);if(error)setAviso(error.message);else setMeusServicos((itens||[]).map(x=>x.servico_id))}
 useEffect(()=>{carregarBase()},[usuario?.id]);useEffect(()=>{carregarAgenda()},[profissionalId,data]);useEffect(()=>{carregarServicos()},[meuProfissional?.id]);

 function abrirAgendamento(){setClienteBusca('');setEditor({cliente_id:'',profissional_id:profissionalId,servico_id:servicosDoEditor[0]?.id||'',data_agendamento:data,hora_inicio:'09:00',situacao:'confirmado',observacao:''})}
 async function salvarAgendamento(e){e.preventDefault();if(!editor.cliente_id)return setAviso('Pesquise e selecione um cliente.');const servico=servicos.find(s=>s.id===editor.servico_id);if(!servico)return setAviso('Selecione um serviço.');setSalvando(true);const fim=new Date(`2000-01-01T${editor.hora_inicio}:00`);fim.setMinutes(fim.getMinutes()+Number(servico.duracao_minutos||30));const carga={...editor,hora_fim:fim.toTimeString().slice(0,5),observacao:editor.observacao||null};delete carga.id;const r=editor.id?await supabase.from('agendamentos').update(carga).eq('id',editor.id):await supabase.from('agendamentos').insert({...carga,empresa_id:usuario.empresa_id});setSalvando(false);if(r.error)setAviso(r.error.message);else{setEditor(null);setAviso('Agendamento salvo com sucesso.');carregarAgenda()}}
 async function excluirAgendamento(item){if(!confirm(`Excluir o horário de ${item.usuarios?.nome||'cliente'}?`))return;const{error}=await supabase.from('agendamentos').delete().eq('id',item.id);if(error)setAviso(error.message);else{setAviso('Agendamento excluído.');carregarAgenda()}}
 async function salvarServico(e){e.preventDefault();if(!meuProfissional)return;setSalvando(true);const carga={empresa_id:usuario.empresa_id,nome:servicoEditor.nome,descricao:servicoEditor.descricao||null,preco:Number(servicoEditor.preco),duracao_minutos:Number(servicoEditor.duracao_minutos),ativo:true};const{data:novo,error}=await supabase.from('servicos').insert(carga).select('id').single();if(!error){const{error:associar}=await supabase.from('profissionais_servicos').insert({profissional_id:meuProfissional.id,servico_id:novo.id});if(associar)setAviso(associar.message)}setSalvando(false);if(error)setAviso(error.message);else{setMeusServicos(ids=>[...ids,novo.id]);setServicoEditor(null);setAviso('Serviço criado e vinculado ao seu perfil. Recarregando a lista...');window.setTimeout(()=>location.reload(),500)}}
 async function alternarServico(id){if(!meuProfissional)return;const existe=meusServicos.includes(id);const r=existe?await supabase.from('profissionais_servicos').delete().eq('profissional_id',meuProfissional.id).eq('servico_id',id):await supabase.from('profissionais_servicos').insert({profissional_id:meuProfissional.id,servico_id:id});if(r.error)setAviso(r.error.message);else setMeusServicos(xs=>existe?xs.filter(x=>x!==id):[...xs,id])}
 async function salvarMembro(e){e.preventDefault();if(!membroEditor.id&&!cpfValido(membroEditor.cpf))return setAviso('Informe um CPF válido para o funcionário.');setSalvando(true);try{const{data:{session}}=await supabase.auth.getSession();const r=await fetch('/.netlify/functions/staff-users',{method:membroEditor.id?'PATCH':'POST',headers:{'content-type':'application/json',authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({...membroEditor,telefone:somenteDigitos(membroEditor.telefone),cpf:somenteDigitos(membroEditor.cpf)})});const corpo=await r.json().catch(()=>({error:'A função administrativa não respondeu.'}));if(!r.ok)throw Error(corpo.error);setMembroEditor(null);setAviso(corpo.message);carregarBase()}catch(e){setAviso(e.message)}finally{setSalvando(false)}}
 async function excluirMembro(m){if(!confirm(`Excluir o acesso de ${m.nome}?`))return;const{data:{session}}=await supabase.auth.getSession();const r=await fetch('/.netlify/functions/staff-users',{method:'DELETE',headers:{'content-type':'application/json',authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({id:m.id})});const corpo=await r.json().catch(()=>({}));if(!r.ok)setAviso(corpo.error||'Não foi possível excluir.');else{setAviso('Funcionário excluído.');carregarBase()}}
 async function salvarPerfil(e){e.preventDefault();setSalvando(true);const{error}=await supabase.from('usuarios').update({nome:perfil.nome,telefone:somenteDigitos(perfil.telefone),cpf:somenteDigitos(perfil.cpf)||null}).eq('id',usuario.id);setSalvando(false);setAviso(error?error.message:'Perfil salvo com sucesso.');}

 return <div className="equipe-shell"><aside className="equipe-sidebar"><button className="equipe-marca" onClick={onInicio}>{empresa?.configuracao_json?.logoText||empresa?.nome||'CASA ÂMBAR'}</button><div className="equipe-usuario"><span>{usuario.nome?.slice(0,1)}</span><div><strong>{usuario.nome}</strong><small>{papelNome(papel)}</small></div></div><nav><button className={aba==='agenda'?'ativo':''} onClick={()=>setAba('agenda')}>Agenda</button><button className={aba==='perfil'?'ativo':''} onClick={()=>setAba('perfil')}>Meu perfil</button>{papel==='profissional'&&<button className={aba==='servicos'?'ativo':''} onClick={()=>setAba('servicos')}>Meus serviços</button>}{gestor&&<button className={aba==='equipe'?'ativo':''} onClick={()=>setAba('equipe')}>Equipe e permissões</button>}</nav><button className="equipe-sair" onClick={onSair}>Sair da conta</button></aside><main className="equipe-conteudo">{aviso&&<p className="equipe-aviso" role="status">{aviso}</p>}
 {aba==='agenda'&&<><header className="equipe-topo"><div><p>PAINEL {gestor?'ADMINISTRATIVO':'PROFISSIONAL'}</p><h1>{gestor?'Agenda e operação do espaço.':'Minha agenda de atendimento.'}</h1></div>{podeEditar&&<button className="equipe-primario" onClick={abrirAgendamento} disabled={!profissionalId}>Adicionar horário</button>}</header>{gestor&&<section className="equipe-profissionais"><p>ESCOLHA O PROFISSIONAL</p><div>{profissionais.map(p=><button key={p.id} className={p.id===profissionalId?'selecionado':''} onClick={()=>setProfissionalId(p.id)}><i>{p.usuarios?.nome?.slice(0,1)}</i>{p.usuarios?.nome}</button>)}</div></section>}<section className="equipe-resumo"><article><small>HORÁRIOS</small><strong>{metricas.total}</strong><span>na agenda</span></article><article><small>CONFIRMADOS</small><strong>{metricas.confirmados}</strong><span>atendimentos</span></article><article><small>PENDENTES</small><strong>{metricas.pendentes}</strong><span>aguardando resposta</span></article></section><section className="equipe-agenda"><header><div><p>AGENDA DE {selecionado?.usuarios?.nome?.toUpperCase()||'...'}</p><h2>{dataBr(data)}</h2></div><label>Data<input type="date" value={data} onChange={e=>setData(e.target.value)}/></label></header>{carregando?<p className="equipe-vazio">Carregando...</p>:agendamentos.length?<div className="equipe-lista">{agendamentos.map(i=><article key={i.id}><time>{hora(i.hora_inicio)}<small>{hora(i.hora_fim)}</small></time><div><strong>{i.usuarios?.nome||'Cliente'}</strong><span>{i.servicos?.nome||'Serviço'}</span><small>{i.observacao||'Sem descrição do cliente.'}</small></div><em className={i.situacao}>{i.situacao}</em>{podeEditar&&<div className="equipe-acoes"><button onClick={()=>setEditor({...i,hora_inicio:hora(i.hora_inicio)})}>Editar</button>{gestor&&<button className="perigo" onClick={()=>excluirAgendamento(i)}>Excluir</button>}</div>}</article>)}</div>:<p className="equipe-vazio">Nenhum horário para esta data.</p>}</section></>}
 {aba==='servicos'&&<section className="equipe-servicos"><header className="equipe-topo"><div><p>PERFIL PROFISSIONAL</p><h1>Meus serviços</h1><span>Crie serviços próprios e deixe-os disponíveis para seus clientes.</span></div><button className="equipe-primario" onClick={()=>setServicoEditor({nome:'',preco:'',duracao_minutos:'30',descricao:''})}>Adicionar serviço</button></header><div className="equipe-servicos-grid">{servicos.map(s=><button key={s.id} className={meusServicos.includes(s.id)?'selecionado':''} onClick={()=>alternarServico(s.id)}><strong>{s.nome}</strong><small>{s.duracao_minutos} min · R$ {Number(s.preco).toFixed(2).replace('.',',')}</small><b>{meusServicos.includes(s.id)?'Disponível':'Adicionar ao meu perfil'}</b></button>)}</div></section>}
 {aba==='equipe'&&<section className="equipe-administracao"><header><div><p>GESTÃO DE ACESSOS</p><h1>Equipe, cargos e permissões.</h1></div><button className="equipe-primario" onClick={()=>setMembroEditor(novoMembro())}>Cadastrar funcionário</button></header><div className="equipe-membros">{membros.map(m=><article key={m.id}><i>{m.nome?.slice(0,1)}</i><div><strong>{m.nome}</strong><span>{m.cargo||'Profissional'} · {papelNome(m.papel)}</span><small>{m.email}</small></div><b>{m.nivel_acesso==='gestor'?'Gestor':'Agenda'}</b><div><button onClick={()=>setMembroEditor({...m,senha:'',cpf:m.cpf||''})}>Editar</button>{m.id!==usuario.id&&<button className="perigo" onClick={()=>excluirMembro(m)}>Excluir</button>}</div></article>)}</div></section>}
 {aba==='perfil'&&<section className="equipe-administracao"><header><div><p>MINHA CONTA</p><h1>Meu perfil</h1></div></header><form className="perfil-form" onSubmit={salvarPerfil}><div className="perfil-grid"><label>Nome<input required value={perfil.nome||''} onChange={e=>setPerfil({...perfil,nome:e.target.value})}/></label><label>E-mail<input disabled value={perfil.email||''}/></label><label>CPF<input inputMode="numeric" value={mascaraCpf(perfil.cpf)} onChange={e=>setPerfil({...perfil,cpf:somenteDigitos(e.target.value)})}/></label><label>Telefone<input inputMode="tel" value={mascaraTelefone(perfil.telefone)} onChange={e=>setPerfil({...perfil,telefone:somenteDigitos(e.target.value)})}/></label></div><footer><button className="equipe-primario" disabled={salvando}>{salvando?'Salvando...':'Salvar alterações'}</button></footer></form></section>}
 </main>
 {editor&&<div className="equipe-modal"><form onSubmit={salvarAgendamento}><button type="button" className="fechar" onClick={()=>setEditor(null)}>×</button><p>AGENDAMENTO</p><h2>{editor.id?'Editar horário':'Novo horário'}</h2><label>Buscar cliente por nome, CPF ou telefone<input value={clienteBusca} onChange={e=>setClienteBusca(e.target.value)} placeholder="Digite para pesquisar"/></label><label>Cliente<select required value={editor.cliente_id} onChange={e=>setEditor({...editor,cliente_id:e.target.value})}><option value="">Selecione um cliente</option>{clientesFiltrados.map(c=><option key={c.id} value={c.id}>{c.nome} · {mascaraTelefone(c.telefone)} · {mascaraCpf(c.cpf)}</option>)}</select></label><label>Profissional<select disabled={!gestor} value={editor.profissional_id} onChange={e=>setEditor({...editor,profissional_id:e.target.value})}>{profissionais.map(p=><option key={p.id} value={p.id}>{p.usuarios?.nome}</option>)}</select></label><label>Serviço<select value={editor.servico_id} onChange={e=>setEditor({...editor,servico_id:e.target.value})}>{servicosDoEditor.map(s=><option key={s.id} value={s.id}>{s.nome}</option>)}</select></label><div className="duplo"><label>Data<input type="date" value={editor.data_agendamento} onChange={e=>setEditor({...editor,data_agendamento:e.target.value})}/></label><label>Horário<input type="time" value={editor.hora_inicio} onChange={e=>setEditor({...editor,hora_inicio:e.target.value})}/></label></div><label>Descrição / pedido<textarea value={editor.observacao||''} onChange={e=>setEditor({...editor,observacao:e.target.value})}/></label><button className="equipe-primario" disabled={salvando}>Salvar horário</button></form></div>}
 {membroEditor&&<div className="equipe-modal"><form onSubmit={salvarMembro}><button type="button" className="fechar" onClick={()=>setMembroEditor(null)}>×</button><p>EQUIPE</p><h2>{membroEditor.id?'Editar funcionário':'Cadastrar funcionário'}</h2><label>Nome<input required value={membroEditor.nome||''} onChange={e=>setMembroEditor({...membroEditor,nome:e.target.value})}/></label><label>CPF<input required inputMode="numeric" value={mascaraCpf(membroEditor.cpf)} onChange={e=>setMembroEditor({...membroEditor,cpf:somenteDigitos(e.target.value)})}/></label><label>Telefone<input required inputMode="tel" value={mascaraTelefone(membroEditor.telefone)} onChange={e=>setMembroEditor({...membroEditor,telefone:somenteDigitos(e.target.value)})}/></label><label>E-mail<input required type="email" value={membroEditor.email||''} onChange={e=>setMembroEditor({...membroEditor,email:e.target.value})}/></label><label>{membroEditor.id?'Nova senha (opcional)':'Senha inicial'}<input required={!membroEditor.id} minLength="3" type="password" value={membroEditor.senha||''} onChange={e=>setMembroEditor({...membroEditor,senha:e.target.value})}/></label><label>Cargo<input required value={membroEditor.cargo||''} onChange={e=>setMembroEditor({...membroEditor,cargo:e.target.value})}/></label><label>Papel<select value={membroEditor.papel} onChange={e=>setMembroEditor({...membroEditor,papel:e.target.value})}><option value="profissional">Profissional</option><option value="caixa">Caixa</option><option value="administrador">Dono(a)</option></select></label><label>Nível de acesso<select value={membroEditor.nivel_acesso} onChange={e=>setMembroEditor({...membroEditor,nivel_acesso:e.target.value})}><option value="visualizador">Agenda própria</option><option value="gestor">Gestor — equipe e agenda</option></select></label><button className="equipe-primario" disabled={salvando}>Salvar funcionário</button></form></div>}
 {servicoEditor&&<div className="equipe-modal"><form onSubmit={salvarServico}><button type="button" className="fechar" onClick={()=>setServicoEditor(null)}>×</button><p>NOVO SERVIÇO</p><h2>O que você realiza?</h2><label>Nome do serviço<input required value={servicoEditor.nome} onChange={e=>setServicoEditor({...servicoEditor,nome:e.target.value})}/></label><div className="duplo"><label>Preço (R$)<input required min="0" step="0.01" type="number" value={servicoEditor.preco} onChange={e=>setServicoEditor({...servicoEditor,preco:e.target.value})}/></label><label>Duração (minutos)<input required min="5" step="5" type="number" value={servicoEditor.duracao_minutos} onChange={e=>setServicoEditor({...servicoEditor,duracao_minutos:e.target.value})}/></label></div><label>Descrição<textarea value={servicoEditor.descricao} onChange={e=>setServicoEditor({...servicoEditor,descricao:e.target.value})}/></label><button className="equipe-primario" disabled={salvando}>Criar serviço</button></form></div>}
 </div>
}
