import React,{useEffect,useMemo,useState}from'react';
import{mascaraCpf,mascaraTelefone,somenteDigitos,cpfValido}from'./brasil';
import{mensagemErro}from'./mensagens';
import'./team-dashboard.css';
import'./team-services-extra.css';
import'./team-schedule-extra.css';
import'./team-polish.css';
import'./team-home.css';
import'./team-fixes.css';

const hoje=()=>new Date().toISOString().slice(0,10);
const hora=v=>String(v||'').slice(0,5);
const papelNome=p=>({administrador:'Dono(a)',caixa:'Caixa',profissional:'Profissional'}[p]||p);
const dataBr=v=>new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long'}).format(new Date(`${v}T12:00:00`));
const novoMembro=()=>({nome:'',email:'',senha:'',telefone:'',cpf:'',cargo:'Cabeleireiro(a)',papel:'profissional',nivel_acesso:'visualizador'});

export default function TeamDashboard({supabase,usuario,empresa,servicos,onInicio,onSair,onUsuarioAtualizado,onServicosAtualizados,perfilInicial}){
 const[aba,setAba]=useState(perfilInicial?'perfil':'agenda'),[profissionais,setProfissionais]=useState([]),[membros,setMembros]=useState([]),[clientes,setClientes]=useState([]),[profissionalId,setProfissionalId]=useState(''),[meuProfissional,setMeuProfissional]=useState(null),[profissionalServicoId,setProfissionalServicoId]=useState(''),[meusServicos,setMeusServicos]=useState([]),[agendamentos,setAgendamentos]=useState([]),[data,setData]=useState(hoje()),[editor,setEditor]=useState(null),[clienteBusca,setClienteBusca]=useState(''),[membroEditor,setMembroEditor]=useState(null),[servicoEditor,setServicoEditor]=useState(null),[servicoExcluir,setServicoExcluir]=useState(null),[perfil,setPerfil]=useState(usuario),[antecedencia,setAntecedencia]=useState(String(empresa?.antecedencia_minima_minutos??45)),[horarioAbertura,setHorarioAbertura]=useState(String(empresa?.horario_abertura||'09:00').slice(0,5)),[horarioFechamento,setHorarioFechamento]=useState(String(empresa?.horario_fechamento||'18:00').slice(0,5)),[profissionalJornadaId,setProfissionalJornadaId]=useState(''),[jornada,setJornada]=useState([]),[aviso,setAvisoInterno]=useState(''),[salvando,setSalvando]=useState(false),[carregando,setCarregando]=useState(false);
 const setAviso=texto=>setAvisoInterno(mensagemErro(texto));
 const papel=usuario?.papel;
 const gestor=['administrador','caixa'].includes(papel)||usuario?.nivel_acesso==='gestor';
 const podeEditar=gestor||papel==='profissional';
 const alvoServicoId=gestor?(profissionalServicoId||profissionalId):meuProfissional?.id;
 const selecionado=profissionais.find(p=>p.id===profissionalId);
 const clientesFiltrados=useMemo(()=>{const termo=somenteDigitos(clienteBusca)||clienteBusca.toLowerCase().trim();if(!termo)return clientes.slice(0,50);return clientes.filter(c=>[c.nome,c.email,somenteDigitos(c.telefone),somenteDigitos(c.cpf)].some(v=>String(v||'').toLowerCase().includes(termo))).slice(0,50)},[clientes,clienteBusca]);
 const servicosDoEditor=useMemo(()=>gestor?servicos:servicos.filter(s=>meusServicos.includes(s.id)),[gestor,servicos,meusServicos]);
 const metricas=useMemo(()=>({total:agendamentos.length,confirmados:agendamentos.filter(a=>a.situacao==='confirmado').length,pendentes:agendamentos.filter(a=>a.situacao==='pendente').length}),[agendamentos]);

 async function carregarBase(){
  if(!usuario?.empresa_id)return;setCarregando(true);
  const[profs,clis,memb,meu]=await Promise.all([
   supabase.from('profissionais').select('id,usuario_id,biografia,usuarios(id,nome,email,telefone,cpf,cargo,papel,nivel_acesso)').eq('empresa_id',usuario.empresa_id).eq('ativo',true).order('criado_em'),
   supabase.from('usuarios').select('id,nome,email,telefone,cpf').eq('empresa_id',usuario.empresa_id).eq('papel','cliente').order('nome'),
   gestor?supabase.from('usuarios').select('id,nome,email,telefone,cpf,cargo,papel,nivel_acesso').eq('empresa_id',usuario.empresa_id).neq('papel','cliente').order('nome'):Promise.resolve({data:[]}),
   supabase.from('profissionais').select('id,usuario_id').eq('usuario_id',usuario.id).maybeSingle()
  ]);
  const erro=profs.error||clis.error||memb.error||meu.error;if(erro)setAviso(erro.message);else{setProfissionais(profs.data||[]);setClientes(clis.data||[]);setMembros(memb.data||[]);setMeuProfissional(meu.data||null);setProfissionalId(id=>id||(gestor?profs.data?.[0]?.id:meu.data?.id)||'');setProfissionalJornadaId(id=>id||(profs.data||[])[0]?.id||'')};setCarregando(false);
 }
 async function carregarAgenda(){if(!profissionalId)return;const{data:itens,error}=await supabase.from('agendamentos').select('id,data_agendamento,hora_inicio,hora_fim,situacao,observacao,cliente_id,profissional_id,servico_id,usuarios(nome,telefone),servicos(nome,duracao_minutos)').eq('profissional_id',profissionalId).eq('data_agendamento',data).order('hora_inicio');if(error)setAviso(error.message);else setAgendamentos(itens||[])}
 async function carregarServicos(){if(!alvoServicoId)return;const{data:itens,error}=await supabase.from('profissionais_servicos').select('servico_id').eq('profissional_id',alvoServicoId);if(error)setAviso(error.message);else setMeusServicos((itens||[]).map(x=>x.servico_id))}
 async function carregarJornada(){if(!profissionalJornadaId)return;const{data:itens,error}=await supabase.from('horarios_trabalho').select('id,dia_semana,hora_inicio,hora_fim').eq('profissional_id',profissionalJornadaId).order('dia_semana').order('hora_inicio');if(error)setAviso(error.message);else setJornada((itens||[]).map(i=>({...i,hora_inicio:hora(i.hora_inicio),hora_fim:hora(i.hora_fim)})))}
 useEffect(()=>{carregarBase()},[usuario?.id]);useEffect(()=>{carregarAgenda()},[profissionalId,data]);useEffect(()=>{carregarServicos()},[alvoServicoId]);useEffect(()=>{carregarJornada()},[profissionalJornadaId]);

 function abrirAgendamento(){setClienteBusca('');setEditor({cliente_id:'',profissional_id:profissionalId,servico_id:servicosDoEditor[0]?.id||'',data_agendamento:data,hora_inicio:'09:00',situacao:'confirmado',observacao:''})}
 async function salvarAgendamento(e){e.preventDefault();if(!editor.cliente_id)return setAviso('Pesquise e selecione um cliente.');const servico=servicos.find(s=>s.id===editor.servico_id);if(!servico)return setAviso('Selecione um serviço.');setSalvando(true);const fim=new Date(`2000-01-01T${editor.hora_inicio}:00`);fim.setMinutes(fim.getMinutes()+Number(servico.duracao_minutos||30));const carga={...editor,hora_fim:fim.toTimeString().slice(0,5),observacao:editor.observacao||null};delete carga.id;const r=editor.id?await supabase.from('agendamentos').update(carga).eq('id',editor.id):await supabase.from('agendamentos').insert({...carga,empresa_id:usuario.empresa_id});setSalvando(false);if(r.error)setAviso(r.error.message);else{setEditor(null);setAviso('Agendamento salvo com sucesso.');carregarAgenda()}}
 async function excluirAgendamento(item){if(!confirm(`Excluir o horário de ${item.usuarios?.nome||'cliente'}?`))return;const{error}=await supabase.from('agendamentos').delete().eq('id',item.id);if(error)setAviso(error.message);else{setAviso('Agendamento excluído.');carregarAgenda()}}
 async function salvarServico(e){e.preventDefault();if(!alvoServicoId)return;setSalvando(true);const carga={empresa_id:usuario.empresa_id,nome:servicoEditor.nome,descricao:servicoEditor.descricao||null,preco:Number(servicoEditor.preco),duracao_minutos:Number(servicoEditor.duracao_minutos),ativo:true};const{data:novo,error}=await supabase.from('servicos').insert(carga).select('id').single();if(!error){const{error:associar}=await supabase.from('profissionais_servicos').insert({profissional_id:alvoServicoId,servico_id:novo.id});if(associar){setSalvando(false);setAviso(associar.message);return}}setSalvando(false);if(error)setAviso(error.message);else{setMeusServicos(ids=>[...ids,novo.id]);setServicoEditor(null);await onServicosAtualizados?.();setAviso('Serviço criado e vinculado ao profissional.')}}
 async function alternarServico(id){if(!alvoServicoId)return;const existe=meusServicos.includes(id);const r=existe?await supabase.from('profissionais_servicos').delete().eq('profissional_id',alvoServicoId).eq('servico_id',id):await supabase.from('profissionais_servicos').insert({profissional_id:alvoServicoId,servico_id:id});if(r.error)setAviso(r.error.message);else setMeusServicos(xs=>existe?xs.filter(x=>x!==id):[...xs,id])}
 async function excluirServico(){if(!servicoExcluir||!alvoServicoId)return;setSalvando(true);const{error:erroVinculo}=await supabase.from('profissionais_servicos').delete().eq('profissional_id',alvoServicoId).eq('servico_id',servicoExcluir.id);if(erroVinculo){setSalvando(false);setAviso(erroVinculo);return}const{data:outros,error:erroOutros}=await supabase.from('profissionais_servicos').select('profissional_id').eq('servico_id',servicoExcluir.id).limit(1);if(erroOutros){setSalvando(false);setAviso(erroOutros);return}let erro=null;if(!(outros||[]).length)({error:erro}=await supabase.from('servicos').update({ativo:false}).eq('id',servicoExcluir.id));setSalvando(false);if(erro){setAviso(erro);return}setMeusServicos(ids=>ids.filter(id=>id!==servicoExcluir.id));setServicoExcluir(null);setAviso((outros||[]).length?'Serviço removido do perfil.':'Serviço desativado. Os agendamentos antigos foram preservados.')}
 async function salvarMembro(e){e.preventDefault();const telefone=somenteDigitos(membroEditor.telefone),cpf=somenteDigitos(membroEditor.cpf);if(!membroEditor.nome?.trim())return setAviso('Informe o nome completo do funcionário.');if(!/^\S+@\S+\.\S+$/.test(membroEditor.email||''))return setAviso('Informe um e-mail válido.');if(!cpfValido(cpf))return setAviso('Informe um CPF válido para o funcionário.');if(!/^\d{10,11}$/.test(telefone))return setAviso('Informe um telefone brasileiro válido com DDD.');if(!membroEditor.id&&String(membroEditor.senha||'').length<3)return setAviso('A senha inicial deve ter ao menos 3 caracteres.');setSalvando(true);try{const{data:{session}}=await supabase.auth.getSession();const r=await fetch('/.netlify/functions/staff-users',{method:membroEditor.id?'PATCH':'POST',headers:{'content-type':'application/json',authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({...membroEditor,telefone,cpf})});const corpo=await r.json().catch(()=>({error:'A função administrativa não respondeu.'}));if(!r.ok)throw Error(corpo.error);setMembroEditor(null);setAviso(corpo.message);carregarBase()}catch(e){setAviso(e)}finally{setSalvando(false)}}
 async function excluirMembro(m){if(!confirm(`Excluir o acesso de ${m.nome}?`))return;const{data:{session}}=await supabase.auth.getSession();const r=await fetch('/.netlify/functions/staff-users',{method:'DELETE',headers:{'content-type':'application/json',authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({id:m.id})});const corpo=await r.json().catch(()=>({}));if(!r.ok)setAviso(corpo.error||'Não foi possível excluir.');else{setAviso('Funcionário excluído.');carregarBase()}}
 async function salvarPerfil(e){e.preventDefault();if(perfil.cpf&&!cpfValido(perfil.cpf))return setAviso('Informe um CPF válido.');setSalvando(true);const{error}=await supabase.from('usuarios').update({nome:perfil.nome,telefone:somenteDigitos(perfil.telefone),cpf:somenteDigitos(perfil.cpf)||null,foto_url:perfil.foto_url||null}).eq('id',usuario.id);setSalvando(false);if(error)return setAviso('Não foi possível salvar o perfil.');onUsuarioAtualizado?.(perfil);setAviso('Perfil salvo com sucesso.');}
 async function enviarFotoPerfil(e){const arquivo=e.target.files?.[0];if(!arquivo)return;if(!arquivo.type.startsWith('image/'))return setAviso('Envie uma imagem JPG, PNG ou WebP.');setSalvando(true);const caminho=`${usuario.usuario_auth_id}/${Date.now()}-${arquivo.name.replace(/[^a-zA-Z0-9.]/g,'')}`;const{error:erroUpload}=await supabase.storage.from('avatares').upload(caminho,arquivo,{upsert:false});if(erroUpload){setSalvando(false);return setAviso(erroUpload)}const{data}=supabase.storage.from('avatares').getPublicUrl(caminho);const{error}=await supabase.from('usuarios').update({foto_url:data.publicUrl}).eq('id',usuario.id);setSalvando(false);if(error)return setAviso(error);setPerfil(atual=>{const atualizado={...atual,foto_url:data.publicUrl};onUsuarioAtualizado?.(atualizado);return atualizado});setAviso('Foto de perfil atualizada com sucesso.');}
 async function salvarAntecedencia(e){e.preventDefault();const minutos=Number(antecedencia);if(!Number.isInteger(minutos)||minutos<0||minutos>240)return setAviso('Informe uma antecedência entre 0 e 240 minutos.');if(papel==='administrador'&&horarioFechamento<=horarioAbertura)return setAviso('O horário de fechamento deve ser depois da abertura.');setSalvando(true);const carga={antecedencia_minima_minutos:minutos};if(papel==='administrador'){carga.horario_abertura=horarioAbertura;carga.horario_fechamento=horarioFechamento}const{error}=await supabase.from('empresas').update(carga).eq('id',usuario.empresa_id);setSalvando(false);setAviso(error?error.message:'Configuração da agenda atualizada.')}
 async function salvarJornada(e){e.preventDefault();if(!profissionalJornadaId)return;for(const item of jornada)if(!item.hora_inicio||!item.hora_fim||item.hora_fim<=item.hora_inicio)return setAviso('Cada turno deve ter início antes do fim.');setSalvando(true);for(const item of jornada){const carga={profissional_id:profissionalJornadaId,dia_semana:Number(item.dia_semana),hora_inicio:item.hora_inicio,hora_fim:item.hora_fim};const r=item.id?await supabase.from('horarios_trabalho').update(carga).eq('id',item.id):await supabase.from('horarios_trabalho').insert(carga);if(r.error){setSalvando(false);setAviso(r.error.message);return}}setSalvando(false);setAviso('Horários do profissional atualizados.');carregarJornada()}
 async function removerTurno(item){if(!item.id)return setJornada(lista=>lista.filter(x=>x!==item));if(!confirm('Remover este turno?'))return;const{error}=await supabase.from('horarios_trabalho').delete().eq('id',item.id);if(error)setAviso(error.message);else{setJornada(lista=>lista.filter(x=>x.id!==item.id));setAviso('Turno removido.')}}

 return <div className="equipe-shell"><aside className="equipe-sidebar"><button className="equipe-marca" onClick={onInicio}>{empresa?.configuracao_json?.logoText||empresa?.nome||'CASA ÂMBAR'}</button><div className="equipe-usuario"><span>{usuario.nome?.slice(0,1)}</span><div><strong>{usuario.nome}</strong><small>{papelNome(papel)}</small></div></div><nav><button className={aba==='agenda'?'ativo':''} onClick={()=>setAba('agenda')}>Agenda</button><button className={aba==='perfil'?'ativo':''} onClick={()=>setAba('perfil')}>Meu perfil</button>{(papel==='profissional'||gestor)&&<button className={aba==='servicos'?'ativo':''} onClick={()=>setAba('servicos')}>{gestor?'Serviços da equipe':'Meus serviços'}</button>}<button className={aba==='configuracoes'?'ativo':''} onClick={()=>setAba('configuracoes')}>Configurar agenda</button>{gestor&&<button className={aba==='equipe'?'ativo':''} onClick={()=>setAba('equipe')}>Equipe e permissões</button>}</nav><button className="equipe-sair" onClick={onSair}>Sair da conta</button></aside><main className="equipe-conteudo">{aviso&&<p className="equipe-aviso" role="status">{aviso}</p>}
 {aba==='agenda'&&<><header className="equipe-topo"><div><p>PAINEL {gestor?'ADMINISTRATIVO':'PROFISSIONAL'}</p><h1>{gestor?'Agenda e operação do espaço.':'Minha agenda de atendimento.'}</h1></div>{podeEditar&&<button className="equipe-primario" onClick={abrirAgendamento} disabled={!profissionalId}>Adicionar horário</button>}</header>{gestor&&<section className="equipe-profissionais"><p>ESCOLHA O PROFISSIONAL</p><div>{profissionais.map(p=><button key={p.id} className={p.id===profissionalId?'selecionado':''} onClick={()=>setProfissionalId(p.id)}><i>{p.usuarios?.nome?.slice(0,1)}</i>{p.usuarios?.nome}</button>)}</div></section>}<section className="equipe-resumo"><article><small>HORÁRIOS</small><strong>{metricas.total}</strong><span>na agenda</span></article><article><small>CONFIRMADOS</small><strong>{metricas.confirmados}</strong><span>atendimentos</span></article><article><small>PENDENTES</small><strong>{metricas.pendentes}</strong><span>aguardando resposta</span></article></section><section className="equipe-agenda"><header><div><p>AGENDA DE {selecionado?.usuarios?.nome?.toUpperCase()||'...'}</p><h2>{dataBr(data)}</h2></div><label>Data<input type="date" value={data} onChange={e=>setData(e.target.value)}/></label></header>{carregando?<p className="equipe-vazio">Carregando...</p>:agendamentos.length?<div className="equipe-lista">{agendamentos.map(i=><article key={i.id}><time>{hora(i.hora_inicio)}<small>{hora(i.hora_fim)}</small></time><div><strong>{i.usuarios?.nome||'Cliente'}</strong><span>{i.servicos?.nome||'Serviço'}</span><small>{i.observacao||'Sem descrição do cliente.'}</small></div><em className={i.situacao}>{i.situacao}</em>{podeEditar&&<div className="equipe-acoes"><button onClick={()=>setEditor({...i,hora_inicio:hora(i.hora_inicio)})}>Editar</button>{gestor&&<button className="perigo" onClick={()=>excluirAgendamento(i)}>Excluir</button>}</div>}</article>)}</div>:<p className="equipe-vazio">Nenhum horário para esta data.</p>}</section></>}
 {aba==='servicos'&&<section className="equipe-servicos"><header className="equipe-topo"><div><p>{gestor?'SERVIÇOS DA EQUIPE':'PERFIL PROFISSIONAL'}</p><h1>{gestor?'Serviços por profissional':'Meus serviços'}</h1><span>{gestor?'Escolha o profissional para definir os serviços que os clientes poderão reservar.':'Crie serviços próprios e deixe-os disponíveis para seus clientes.'}</span></div><button className="equipe-primario" onClick={()=>setServicoEditor({nome:'',preco:'',duracao_minutos:'30',descricao:''})} disabled={!alvoServicoId}>Adicionar serviço</button></header>{gestor&&<label className="servico-profissional">Profissional<select value={profissionalServicoId||profissionalId} onChange={e=>setProfissionalServicoId(e.target.value)}>{profissionais.map(p=><option key={p.id} value={p.id}>{p.usuarios?.nome}</option>)}</select></label>}<div className="equipe-servicos-grid">{servicos.map(s=><article key={s.id} className={meusServicos.includes(s.id)?'selecionado':''}><button className="servico-card" onClick={()=>alternarServico(s.id)}><strong>{s.nome}</strong><small>{s.duracao_minutos} min · R$ {Number(s.preco).toFixed(2).replace('.',',')}</small><b>{meusServicos.includes(s.id)?'Disponível':gestor?'Adicionar ao profissional':'Adicionar ao meu perfil'}</b></button>{meusServicos.includes(s.id)&&<button className="servico-excluir" type="button" onClick={()=>setServicoExcluir(s)}>Excluir</button>}</article>)}</div></section>}
 {aba==='equipe'&&<section className="equipe-administracao"><header><div><p>GESTÃO DE ACESSOS</p><h1>Equipe, cargos e permissões.</h1></div><button className="equipe-primario" onClick={()=>setMembroEditor(novoMembro())}>Cadastrar funcionário</button></header><div className="equipe-membros">{membros.map(m=><article key={m.id}><i>{m.nome?.slice(0,1)}</i><div><strong>{m.nome}</strong><span>{m.cargo||'Profissional'} · {papelNome(m.papel)}</span><small>{m.email}</small></div><b>{m.nivel_acesso==='gestor'?'Gestor':'Agenda'}</b><div><button onClick={()=>setMembroEditor({...m,senha:'',cpf:m.cpf||''})}>Editar</button>{m.id!==usuario.id&&<button className="perigo" onClick={()=>excluirMembro(m)}>Excluir</button>}</div></article>)}</div></section>}
 {aba==='perfil'&&<section className="perfil-equipe"><header className="perfil-equipe-capa"><div className="perfil-equipe-avatar">{perfil.foto_url?<img src={perfil.foto_url} alt="Foto de perfil"/>:<span>{perfil.nome?.slice(0,1)}</span>}<label>Alterar foto<input type="file" accept="image/png,image/jpeg,image/webp" onChange={enviarFotoPerfil}/></label></div><div><p>MINHA CONTA</p><h1>{perfil.nome}</h1><span>{perfil.email}</span><b>{papelNome(papel)}</b></div></header><form className="perfil-form" onSubmit={salvarPerfil}><h2>Dados pessoais</h2><div className="perfil-grid"><label>Nome completo<input required value={perfil.nome||''} onChange={e=>setPerfil({...perfil,nome:e.target.value})}/></label><label>E-mail<input disabled value={perfil.email||''}/><small>O e-mail de acesso é alterado pela administração.</small></label><label>CPF<input inputMode="numeric" value={mascaraCpf(perfil.cpf)} onChange={e=>setPerfil({...perfil,cpf:somenteDigitos(e.target.value)})} placeholder="000.000.000-00"/></label><label>Telefone<input inputMode="tel" value={mascaraTelefone(perfil.telefone)} onChange={e=>setPerfil({...perfil,telefone:somenteDigitos(e.target.value)})} placeholder="(00) 00000-0000"/></label></div><footer><button className="equipe-primario" disabled={salvando}>{salvando?'Salvando...':'Salvar alterações'}</button></footer></form></section>}
 {aba==='configuracoes'&&<section className="equipe-administracao"><header><div><p>CONFIGURAÇÃO DA AGENDA</p><h1>Disponibilidade e horários</h1></div></header><form className="perfil-form" onSubmit={salvarAntecedencia}><p>Clientes só verão horários em intervalos de 30 minutos que respeitem a antecedência mínima e o horário de funcionamento.</p><div className="perfil-grid"><label>Antecedência mínima (minutos)<input required inputMode="numeric" min="0" max="240" step="5" type="number" value={antecedencia} onChange={e=>setAntecedencia(e.target.value)}/><small>Exemplo: às 15:06, com 45 minutos, o primeiro horário possível é 16:00.</small></label>{papel==='administrador'&&<><label>Empresa abre às<input required type="time" value={horarioAbertura} onChange={e=>setHorarioAbertura(e.target.value)}/></label><label>Empresa fecha às<input required type="time" value={horarioFechamento} onChange={e=>setHorarioFechamento(e.target.value)}/></label></>}</div><footer><button className="equipe-primario" disabled={salvando}>{salvando?'Salvando...':'Salvar configuração'}</button></footer></form>{gestor&&<form className="perfil-form jornada-form" onSubmit={salvarJornada}><h2>Horário de cada funcionário</h2><p>O cliente só verá horários dentro da jornada configurada para o profissional e antes do fechamento do estabelecimento.</p><label>Profissional<select value={profissionalJornadaId} onChange={e=>setProfissionalJornadaId(e.target.value)}>{profissionais.map(p=><option key={p.id} value={p.id}>{p.usuarios?.nome}</option>)}</select></label><div className="jornada-lista">{jornada.map((item,index)=><div key={item.id||`novo-${index}`}><label>Dia<select value={item.dia_semana} onChange={e=>setJornada(lista=>lista.map((x,i)=>i===index?{...x,dia_semana:e.target.value}:x))}><option value="0">Domingo</option><option value="1">Segunda</option><option value="2">Terça</option><option value="3">Quarta</option><option value="4">Quinta</option><option value="5">Sexta</option><option value="6">Sábado</option></select></label><label>Início<input type="time" value={item.hora_inicio} onChange={e=>setJornada(lista=>lista.map((x,i)=>i===index?{...x,hora_inicio:e.target.value}:x))}/></label><label>Fim<input type="time" value={item.hora_fim} onChange={e=>setJornada(lista=>lista.map((x,i)=>i===index?{...x,hora_fim:e.target.value}:x))}/></label><button type="button" className="perigo" onClick={()=>removerTurno(item)}>Remover</button></div>)}</div><button type="button" onClick={()=>setJornada(lista=>[...lista,{dia_semana:'1',hora_inicio:horarioAbertura,hora_fim:horarioFechamento}])}>Adicionar turno</button><button className="equipe-primario" disabled={salvando}>Salvar horários do profissional</button></form>}</section>}
 </main>
 {editor&&<div className="equipe-modal"><form onSubmit={salvarAgendamento}><button type="button" className="fechar" onClick={()=>setEditor(null)}>×</button><p>AGENDAMENTO</p><h2>{editor.id?'Editar horário':'Novo horário'}</h2><label>Buscar cliente por nome, CPF ou telefone<input value={clienteBusca} onChange={e=>setClienteBusca(e.target.value)} placeholder="Digite para pesquisar"/></label><label>Cliente<select required value={editor.cliente_id} onChange={e=>setEditor({...editor,cliente_id:e.target.value})}><option value="">Selecione um cliente</option>{clientesFiltrados.map(c=><option key={c.id} value={c.id}>{c.nome} · {mascaraTelefone(c.telefone)} · {mascaraCpf(c.cpf)}</option>)}</select></label><label>Profissional<select disabled={!gestor} value={editor.profissional_id} onChange={e=>setEditor({...editor,profissional_id:e.target.value})}>{profissionais.map(p=><option key={p.id} value={p.id}>{p.usuarios?.nome}</option>)}</select></label><label>Serviço<select value={editor.servico_id} onChange={e=>setEditor({...editor,servico_id:e.target.value})}>{servicosDoEditor.map(s=><option key={s.id} value={s.id}>{s.nome}</option>)}</select></label><div className="duplo"><label>Data<input type="date" value={editor.data_agendamento} onChange={e=>setEditor({...editor,data_agendamento:e.target.value})}/></label><label>Horário<input type="time" value={editor.hora_inicio} onChange={e=>setEditor({...editor,hora_inicio:e.target.value})}/></label></div><label>Descrição / pedido<textarea value={editor.observacao||''} onChange={e=>setEditor({...editor,observacao:e.target.value})}/></label><button className="equipe-primario" disabled={salvando}>Salvar horário</button></form></div>}
 {membroEditor&&<div className="equipe-modal"><form onSubmit={salvarMembro}><button type="button" className="fechar" onClick={()=>setMembroEditor(null)}>×</button><p>EQUIPE</p><h2>{membroEditor.id?'Editar funcionário':'Cadastrar funcionário'}</h2><label>Nome<input required value={membroEditor.nome||''} onChange={e=>setMembroEditor({...membroEditor,nome:e.target.value})}/></label><label>CPF<input required inputMode="numeric" value={mascaraCpf(membroEditor.cpf)} onChange={e=>setMembroEditor({...membroEditor,cpf:somenteDigitos(e.target.value)})}/></label><label>Telefone<input required inputMode="tel" value={mascaraTelefone(membroEditor.telefone)} onChange={e=>setMembroEditor({...membroEditor,telefone:somenteDigitos(e.target.value)})}/></label><label>E-mail<input required type="email" value={membroEditor.email||''} onChange={e=>setMembroEditor({...membroEditor,email:e.target.value})}/></label><label>{membroEditor.id?'Nova senha (opcional)':'Senha inicial'}<input required={!membroEditor.id} minLength="3" type="password" value={membroEditor.senha||''} onChange={e=>setMembroEditor({...membroEditor,senha:e.target.value})}/></label><label>Cargo<input required value={membroEditor.cargo||''} onChange={e=>setMembroEditor({...membroEditor,cargo:e.target.value})}/></label><label>Papel<select value={membroEditor.papel} onChange={e=>setMembroEditor({...membroEditor,papel:e.target.value})}><option value="profissional">Profissional</option><option value="caixa">Caixa</option><option value="administrador">Dono(a)</option></select></label><label>Nível de acesso<select value={membroEditor.nivel_acesso} onChange={e=>setMembroEditor({...membroEditor,nivel_acesso:e.target.value})}><option value="visualizador">Agenda própria</option><option value="gestor">Gestor — equipe e agenda</option></select></label><button className="equipe-primario" disabled={salvando}>Salvar funcionário</button></form></div>}
 {servicoEditor&&<div className="equipe-modal"><form onSubmit={salvarServico}><button type="button" className="fechar" onClick={()=>setServicoEditor(null)}>×</button><p>NOVO SERVIÇO</p><h2>O que você realiza?</h2><label>Nome do serviço<input required value={servicoEditor.nome} onChange={e=>setServicoEditor({...servicoEditor,nome:e.target.value})}/></label><div className="duplo"><label>Preço (R$)<input required min="0" step="0.01" type="number" value={servicoEditor.preco} onChange={e=>setServicoEditor({...servicoEditor,preco:e.target.value})}/></label><label>Duração (minutos)<input required min="5" step="5" type="number" value={servicoEditor.duracao_minutos} onChange={e=>setServicoEditor({...servicoEditor,duracao_minutos:e.target.value})}/></label></div><label>Descrição<textarea value={servicoEditor.descricao} onChange={e=>setServicoEditor({...servicoEditor,descricao:e.target.value})}/></label><button className="equipe-primario" disabled={salvando}>Criar serviço</button></form></div>}
 {servicoExcluir&&<div className="equipe-modal"><section className="confirmar-exclusao" role="dialog" aria-modal="true" aria-labelledby="titulo-excluir-servico"><button type="button" className="fechar" onClick={()=>setServicoExcluir(null)} aria-label="Fechar">×</button><p>EXCLUIR SERVIÇO</p><h2 id="titulo-excluir-servico">Excluir “{servicoExcluir.nome}”?</h2><span>Se outro profissional também usa este serviço, ele será removido apenas do seu perfil. Caso contrário, será excluído do catálogo.</span><div><button type="button" onClick={()=>setServicoExcluir(null)}>Cancelar</button><button type="button" className="perigo" disabled={salvando} onClick={excluirServico}>{salvando?'Excluindo...':'Excluir serviço'}</button></div></section></div>}
 </div>
}
